foreach(required IN ITEMS ELF NM READELF ABI)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "missing ${required}")
  endif()
endforeach()
if(NOT EXISTS "${ELF}")
  message(FATAL_ERROR "LSPlant bridge ELF does not exist: ${ELF}")
endif()
execute_process(COMMAND "${READELF}" -W -h -l -d "${ELF}"
  RESULT_VARIABLE readelf_result OUTPUT_VARIABLE elf_text ERROR_VARIABLE elf_error)
if(NOT readelf_result EQUAL 0)
  message(FATAL_ERROR "llvm-readelf failed: ${elf_error}")
endif()
execute_process(COMMAND "${NM}" -D --defined-only "${ELF}"
  RESULT_VARIABLE nm_result OUTPUT_VARIABLE symbols ERROR_VARIABLE nm_error)
if(NOT nm_result EQUAL 0)
  message(FATAL_ERROR "llvm-nm failed: ${nm_error}")
endif()
if(NOT elf_text MATCHES "Type:[ \t]+DYN")
  message(FATAL_ERROR "LSPlant bridge is not ET_DYN")
endif()
if(ABI STREQUAL "arm64-v8a" AND NOT elf_text MATCHES "Machine:[ \t]+AArch64")
  message(FATAL_ERROR "arm64 bridge has wrong ELF machine")
elseif(ABI STREQUAL "armeabi-v7a" AND NOT elf_text MATCHES "Machine:[ \t]+ARM")
  message(FATAL_ERROR "arm32 bridge has wrong ELF machine")
endif()
if(elf_text MATCHES "Shared library: \[libc\+\+_shared.so\]")
  message(FATAL_ERROR "LSPlant bridge depends on libc++_shared.so")
endif()
if(elf_text MATCHES "(^|\n)[ \t]*TLS[ \t]+")
  message(FATAL_ERROR "LSPlant bridge contains PT_TLS")
endif()
foreach(name IN ITEMS
    pathguard_lsplant_initialize_v1
    pathguard_lsplant_install_passthrough_v1
    pathguard_lsplant_wait_passthrough_v1)
  if(NOT symbols MATCHES "[ \t]${name}(@@PATHGUARD_LSPLANT_1.0)?(\n|$)")
    message(FATAL_ERROR "LSPlant bridge export missing: ${name}")
  endif()
endforeach()
if(symbols MATCHES "[ \t](lsplant::|_ZN7lsplant|DobbyHook|xdl_open)(\n|@)")
  message(FATAL_ERROR "LSPlant implementation symbol escaped the C ABI")
endif()
