if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "SOURCE_DIR is required")
endif()

file(READ "${SOURCE_DIR}/rules/CMakeLists.txt" rules_cmake)
file(READ "${SOURCE_DIR}/core/CMakeLists.txt" core_cmake)
file(READ "${SOURCE_DIR}/native/Android.mk" android_mk)

if(NOT rules_cmake MATCHES "add_library\\(pathguard_rules_compiler STATIC")
  message(FATAL_ERROR "missing unique pathguard_rules_compiler target")
endif()
if(rules_cmake MATCHES "add_library\\(pathguard_rules STATIC")
  message(FATAL_ERROR "legacy pathguard_rules target remains")
endif()
if(core_cmake MATCHES "rules/|toml|semantic|desugar")
  message(FATAL_ERROR "policy/core target depends on rules compiler")
endif()
if(NOT android_mk MATCHES "LOCAL_MODULE := pathguard_rules_compiler")
  message(FATAL_ERROR "Android build is missing rules compiler target")
endif()
if(NOT android_mk MATCHES "LOCAL_MODULE := pathguard_rules_parity_probe")
  message(FATAL_ERROR "Android build is missing parity probe")
endif()

string(FIND "${android_mk}" "LOCAL_MODULE := pathguard_zygisk" zygisk_begin)
if(zygisk_begin EQUAL -1)
  message(FATAL_ERROR "Zygisk target not found")
endif()
string(SUBSTRING "${android_mk}" ${zygisk_begin} -1 zygisk_block)
if(DEFINED INJECT_ZYGISK_COMPILER AND INJECT_ZYGISK_COMPILER)
  string(APPEND zygisk_block " ../rules/src/compiler.cpp")
endif()
if(zygisk_block MATCHES "rules/src|pathguard_rules_compiler|tomlplusplus")
  message(FATAL_ERROR "Zygisk source/dependency contains rules compiler")
endif()
