# PathGuard rules format 2.
format = 2

[compatibility]
allow_legacy_mount = true

[apps."org.localsend.localsend_app"]
users = [0]
provider = { enabled = true }
deny_rules = [
    { select = { root = "Pictures", glob = "Nagram", type = "directory" } },
    { select = { root = "DCIM", glob = "Screenshots", type = "directory" } },
]
redirect_rules = [
    { select = { root = "Download", glob = "localsend-source", type = "directory" }, to = "Download/localsend-redirect" },
    { select = { root = "Download/localsend-source", glob = "**", type = "file" }, to = "Download/localsend-redirect" },
    { select = { root = "Download/localsend-source", glob = "**", type = "file" }, to = "Download/localsend-redirect", enforcement = "provider", audit = true },
    { select = { root = "Pictures", glob = "**", type = "file" }, to = "Download/localsend-redirect" },
    { select = { root = "Pictures", glob = "**", type = "file" }, to = "Download/localsend-redirect", enforcement = "provider", audit = true },
]
