if(NOT DEFINED REPORT OR REPORT STREQUAL "")
  message(FATAL_ERROR "missing_argument:REPORT")
endif()
if(NOT EXISTS "${REPORT}" OR IS_DIRECTORY "${REPORT}")
  message(FATAL_ERROR "report_not_found:${REPORT}")
endif()
if(NOT REPORT MATCHES "\\.json$")
  message(FATAL_ERROR "unsupported_report_format")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/comparison_report_schema_v1.cmake")

file(READ "${REPORT}" report_json)
string(JSON root_type ERROR_VARIABLE root_error TYPE "${report_json}")
if(NOT root_error STREQUAL "NOTFOUND" OR NOT root_type STREQUAL "OBJECT")
  message(FATAL_ERROR "invalid_json")
endif()

function(require_field field expected_type)
  string(JSON actual_type ERROR_VARIABLE field_error
    TYPE "${report_json}" "${field}")
  if(NOT field_error STREQUAL "NOTFOUND")
    message(FATAL_ERROR "missing_field:${field}")
  endif()
  if(NOT actual_type STREQUAL expected_type)
    message(FATAL_ERROR
      "invalid_type:${field}:expected=${expected_type}:actual=${actual_type}")
  endif()
endfunction()

function(require_nonempty_string field)
  require_field("${field}" STRING)
  string(JSON value GET "${report_json}" "${field}")
  string(STRIP "${value}" value)
  if(value STREQUAL "")
    message(FATAL_ERROR "empty_field:${field}")
  endif()
endfunction()

require_field(comparison_report_format NUMBER)
string(JSON report_format GET "${report_json}" comparison_report_format)
if(NOT report_format EQUAL PATHGUARD_COMPARISON_REPORT_FORMAT)
  message(FATAL_ERROR "unsupported_report_format:${report_format}")
endif()

foreach(field IN LISTS PATHGUARD_COMPARISON_REPORT_STRING_FIELDS)
  require_nonempty_string("${field}")
endforeach()

foreach(field IN LISTS PATHGUARD_COMPARISON_REPORT_OBJECT_FIELDS)
  require_field("${field}" OBJECT)
  string(JSON item_count LENGTH "${report_json}" "${field}")
  if(item_count EQUAL 0)
    message(FATAL_ERROR "empty_field:${field}")
  endif()
endforeach()

foreach(field IN LISTS PATHGUARD_COMPARISON_REPORT_ARRAY_FIELDS)
  require_field("${field}" ARRAY)
  string(JSON item_count LENGTH "${report_json}" "${field}")
  if(item_count EQUAL 0)
    message(FATAL_ERROR "empty_field:${field}")
  endif()
  math(EXPR last_index "${item_count} - 1")
  foreach(index RANGE 0 ${last_index})
    string(JSON item_type TYPE "${report_json}" "${field}" ${index})
    string(JSON item GET "${report_json}" "${field}" ${index})
    string(STRIP "${item}" item)
    if(NOT item_type STREQUAL "STRING" OR item STREQUAL "")
      message(FATAL_ERROR "invalid_item:${field}:${index}")
    endif()
  endforeach()
endforeach()

string(JSON classification GET "${report_json}" classification)
if(NOT classification IN_LIST PATHGUARD_COMPARISON_REPORT_CLASSIFICATIONS)
  message(FATAL_ERROR "invalid_classification:${classification}")
endif()
